### PR TITLE
Add ecdsa support

### PR DESCRIPTION
**Pull request by colincoleman**
Update includes a format change to be PEP 8 compliant

### CODE REVIEW

**Comment by colincoleman** [comment]
Updated to use correct OID value

**Comment by g-a-d** [comment]
Thanks for the contribution @colincoleman , glad you're finding the project useful! I'll try and get some time to review over this weekend.

**Comment by colincoleman** [comment]
Hi - someone reached out to me earlier this week about this repo and my PR.
Is there anything you would like me to fix or clarify before this PR can be merged?

**Comment by g-a-d** [comment]
Hi @colincoleman , sorry I completely forgot about this. Looking at the diff I think your commits have altered the indentation meaning that it's not easy to see the actual changes - it looks like every line is changed when actually it's just the indentation.
Could you re-submit with the same indentation scheme? (I think it's 3 spaces instead of 4). That way the PR accurately reflects the actual changes. Thanks!

**Comment by g-a-d** [comment]
> Hi @colincoleman , sorry I completely forgot about this. Looking at the diff I think your commits have altered the indentation meaning that it's not easy to see the actual changes - it looks like every line is changed when actually it's just the indentation. Could you re-submit with the same indentation scheme? (I think it's 3 spaces instead of 4). That way the PR accurately reflects the actual changes. Thanks!

Actually, noticed your PEP8 compliance note at the top. I'll just go with this and merge. Thanks for the contribution and sorry for the delay.

**Pull request merged**
